# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9df560d56b8bff07547f0f4e0cfd86cf160da4e572c90a98340d54c7fd39343e65662c12b7de93beb9a39eadbe4d397bd4c110860308be25e2b7af5d6247d0ec

test:
  secret_key_base: 490989ef1aafdd6ea28b9e8aef0f38d2706d58131192a694c2e745f37ba2df16c84ccd7d32a51dcbe7d183b9eabe13e5a77150655463a9e5922712f05a329b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
